env:
  browser: true
  es6: true
extends: airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  func-names: 0
  comma-dangle: 0
  no-param-reassign: 0
  no-console: 0
  no-underscore-dangle: 0
  import/newline-after-import: 0
  prefer-arrow-callback: 0
